### ISSUE TITLE
Install script does not add the source line to .zshrc when using zsh

### ISSUE THREAD

**Issue by AnaBatinovic** [larics/uav_ros_simulation#2]
My default shell is zsh. After installation, these lines were not added to my .zshrc file:
```
# MRS shell configuration 
source /home/ana/uav_ros_simulation/ros_packages/uav_ros_stack/miscellaneous/shell_additions/shell_scripts.sh 
source /home/ana/uav_ros_simulation/.gitman/ardupilot/Tools/completion/completion.zsh 
```
Also, instead of ` source /root/uav_ws/devel/setup.zsh ` there was `source /root/uav_ws/devel/setup.bash`.
I solved it by manually adding and editing those lines according to your instructions.

**Comment by lmark1** [comment]
Get the shell name with the following line:
```
SNAME=$( echo "$SHELL" | grep -Eo '[^/]+/?$' )
```
